### ISSUE TITLE
Chatty McChatBot

### ISSUE THREAD

**Issue by spences10** [javierojeda94/jo-twitter-bot#1]
Hi @javierojeda94, 

Consider using [npm chatbot](https://www.npmjs.com/package/chatbot) :robot: if you want to implement some form of chatbot

**Comment by javierojeda94** [comment]
Thanks! I've been looking for an AI these days. I ended up reading [this comparison](http://stackoverflow.com/questions/37215188/comparison-between-luis-ai-vs-api-ai-vs-wit-ai) but I wasn't convinced by any of these options.

I will give a try to your suggestion. Thanks a lot!

**Comment by spences10** [comment]
Yeah, I'll be honest I haven't seen anything that looks that interesting and easy to apply to the Twitter  API. I'll be watching 😄 see how it turns out 👍

**Comment by javierojeda94** [comment]
Update!
I tried this npm-chatbot but it doesn't fit my bot since it requires an input field to be there in order to work

However, thanks for the suggestion :)

PS: I found this awesome project which i will use insted! https://recast.ai/
